function [positive_set, negative_set] = partition_data_set(data_set, ...
                                                  cls);
%split data into positive set and negative set
goods = cellfun(@(x)find(( ismember({x.objects.class},cls) & ...
                           ([x.objects.truncated]==0) & ...
                           ([x.objects.difficult]==0))),...
                data_set,'UniformOutput',false);

data_set = cellfun(@(x,y)setfield(x,'objects',x.objects(y)),data_set, ...
                  goods,'UniformOutput',false);

%prune empties
pos_length = cellfun(@(x)numel(x.objects)>0,pos_set);
pos_set2 = pos_set(find(pos_length));
neg_set2 = pos_set(find(pos_length)==0);
