function ims = dump_turk_cows;
VOCinit;

resdir = '/nfs/baikal/tmalisie/turk/';
cls = 'cow';
%asp = 'Right';
fg = get_pascal_bg('trainval',cls);

files = cell(0,1);
ims = cell(0,1);

for i = 1:length(fg)
  fprintf(1,'.');
  [tmp,curid,tmp] = fileparts(fg{i});
  recs = PASreadrecord(sprintf(VOCopts.annopath,curid));  
  Ibase = imread(sprintf(VOCopts.imgpath,curid));
  Ibase = im2double(Ibase);
  c = {recs.objects.class};
  bbs = cat(1,recs.objects.bbox);
  goods = find(ismember(c,{cls}));
  for j = 1:length(goods)
    b = bbs(goods(j),:);
    
    if (recs.objects(goods(j)).difficult | recs.objects(goods(j)).truncated ...
        | recs.objects(goods(j)).difficult)
      continue
    end
    
    %if ~strcmp(recs.objects(goods(j)).view,asp)
    %  continue
    %end

    files{end+1}=sprintf('"%s.%05d.png"',curid,goods(j));
    ims{end+1}=sprintf('%s.%05d.png',curid,goods(j));
    
    W = .2*(b(4) -b(2) +1);
    H = .2*(b(3) -b(1) +1);
    b(1) = b(1) - H;
    b(3) = b(3) + H;
    b(2) = b(2) - W;
    b(4) = b(4) + W;
    b = round(b);
    b = clip_to_image(b,[1 1 size(Ibase,2) size(Ibase,1)]);
    
    subI = Ibase(b(2):b(4),b(1):b(3),:);
    factor = 200/max(size(subI,2),size(subI,1));
    subI = max(0.0,min(1.0,imresize(subI,factor)));
    imwrite(subI,sprintf('%s/%s.%05d.png',resdir,curid,goods(j)));
  end
  %drawnow
  %2pause(.1)   
end


filer = fopen(sprintf('~/www/turank/%s.js',cls),'w');
fprintf(filer,'//Autogenerated script\n');
fprintf(filer,'window.selfname = "%s.js";',cls);
fprintf(filer,'window.itembase="http://balaton.graphics.cs.cmu.edu/files/turk/"\n');
fprintf(filer,'window.items = [');
for i = 1:length(files)
  fprintf(filer,'%s, // item %d\n',files{i},i);
end
fprintf(filer,'%s]',files{end});
fclose(filer);

for i = 1:length(ims)
  ims{i} = ['http://balaton.graphics.cs.cmu.edu/files/turk/' ...
            ims{i}];
end


target = 38;
fid = fopen(sprintf('~/www/turank/%s.%d.csv',cls,target),'w');

fprintf(fid,'reference_url,image1_url,image2_url,image3_url,image4_url,image5_url,image6_url,image7_url,image8_url\n');
K = 9;

for P = 1:500
for i= target:target
  possibles = setdiff(1:length(ims),i);
  r = randperm(length(possibles));
  r = possibles(r);
  r = r(1:(K-1));
  r = [i r];
  fprintf(fid,'%s',ims{i});
  for j = 2:length(r)
    fprintf(fid,',%s',ims{r(j)});
  end
  
  fprintf(fid,'\n');
  if length(r)~=length(unique(r))
    fprintf(1,'R not unqiue\n');
    error;
  end
end
end
fclose(fid);

