function dump_turk_suns(X,ids,y,catnames)
VOCinit;

if ~exist('ids','var')
  [X,ids,y,catnames] = sun_initialize('Training_01');
end

targety = find(ismember(catnames,{'/c/control_tower/outdoor/'}));
hits = find(y==targety);

cls = 'sun397';
asp = num2str(targety);

resdir = '/nfs/baikal/tmalisie/turk';

files = cell(0,1);

for i = 1:length(hits)

  [tmp,r1,r2] = fileparts(ids{hits(i)});
  r = [r1 r2];
  files{end+1}=sprintf('%s/%s',resdir,r);
  subI = convert_to_I(ids{hits(i)});
  subI = max(0.0,min(1.0,imresize(subI,[200 200])));
  imwrite(subI,files{end});

end

filer = fopen(sprintf('~/www/turank/%s.%s.js',cls,asp),'w');
fprintf(filer,'//Autogenerated script\n');
fprintf(filer,'K1 = 2; K2 = 4; Ntasks = 5;\n');
fprintf(filer,'window.selfname = "%s.%s.js";\n',cls,asp);
fprintf(filer,'window.itembase="http://balaton.graphics.cs.cmu.edu/files/turk/"\n');
fprintf(filer,'window.items = [');
for i = 1:length(files)-1
  [a,b,c] = fileparts(files{i});
  files{i} = [b c];
  fprintf(filer,'"%s", // item %d\n',files{i},i);
end
[a,b,c] = fileparts(files{end});
files{end} = [b c];
fprintf(filer,'"%s"] // item LAST',files{end});
fclose(filer);